name: Mise a jour automatique de veille.json

on:
  schedule:
    - cron: '0 */6 * * *'  # S'exécute toutes les 6 heures
  workflow_dispatch:        # Permet aussi un lancement manuel

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - run: pip install feedparser
      
      - run: python generate_data.py
      
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add veille.json
          git diff-index --quiet HEAD || git commit -m "auto: mise a jour de veille.json"
          git push
