name: Mise a jour automatique de data.json

on:
  schedule:
    # 5h12 UTC = 7h12 heure française (en heure d'été)
    - cron: '12 5 * * *'
  workflow_dispatch:

# OBLIGATOIRE : Donne le droit au bot de faire "git push"
permissions:
  contents: write

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - run: pip install feedparser

      - run: python generate_data.py

      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          git diff-index --quiet HEAD || git commit -m "auto: mise a jour de data.json"
          git push
